title: selinuxuser.land
description: Guides, tools and workshops for learning how to write great SELinux policy
url: "https://selinuxuser.land"
baseurl: "/"
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
search_enabled: true
remote_theme: just-the-docs/just-the-docs
exclude: [vendor]
